const { cmd, commands } = require('../command');
const axios = require('axios');
const FormData = require('form-data');
const { downloadContentFromMessage } = require('@whiskeysockets/baileys');

cmd({
    pattern: "banana",
    alias: ["nano", "gemini"], 
    desc: "Generate AI image from a reference image",
    category: "ai",
    react: "🎨",
    filename: __filename
},
async (conn, mek, m, { from, quoted, body, isCmd, command, args, q, isGroup, sender, reply }) => {
    try {
        // 1. Image detection logic
        let q_msg = m.quoted ? m.quoted : m;
        let mime = (q_msg.msg || q_msg).mimetype || '';
        
        if (!/image/.test(mime)) return reply("❌ Please reply to an image to use this command.");
        if (!q) return reply("❌ Please provide a prompt.\nExample: .nano make it a king");

        reply("Please wait processing your image 🎨");

        // 2. Download Image Buffer (Fixed Method)
        let download = await q_msg.download();
        if (!download) return reply("❌ Failed to download image. Try again.");

        // 3. Upload to Catbox
        let ext = mime.split("/")[1] || "jpg";
        let imageUrl = await uploadToCatbox(download, ext);

        if (!imageUrl) return reply("❌ Failed to upload image to server.");

        // 4. API Call
        let apiEndpoint = `https://api.nekolabs.web.id/image-generation/nano-banana/v3?prompt=${encodeURIComponent(q)}&imageUrl=${encodeURIComponent(imageUrl)}`;
        
        let response = await axios.get(apiEndpoint);
        let data = response.data;

        // 5. Result Sending
        if (data.success && data.result) {
            await conn.sendMessage(from, { 
                image: { url: data.result }, 
                caption: `*Generated by Nano Banana* 🪄\n\n*Prompt:* ${q}` 
            }, { quoted: mek });
        } else {
            reply("❌ API Error: Image could not be generated.");
        }

    } catch (e) {
        console.log(e);
        reply("❌ System Error: " + e.message);
    }
});

// Catbox Uploader
async function uploadToCatbox(buffer, ext) {
    try {
        let form = new FormData();
        form.append('reqtype', 'fileupload');
        form.append('userhash', ''); 
        form.append('fileToUpload', buffer, `image.${ext}`);

        let res = await axios.post('https://catbox.moe/user/api.php', form, {
            headers: form.getHeaders()
        });
        return res.data; 
    } catch (err) {
        return null;
    }
}
