const { cmd } = require('../command');
const axios = require('axios');
const FormData = require('form-data');

cmd({
    pattern: "fakedev",
    alias: ["fakedev1", "fakedev2", "fakedev3"],
    react: "🎨",
    desc: "Generate a fake developer profile image.",
    category: "maker",
    use: ".fakedev1 Name true (reply image)",
    filename: __filename
}, async (conn, mek, m, { from, reply, text, command, prefix }) => { // 'prefix' instead of 'usedPrefix'
    
    const msgKey = m?.key || mek?.key || null;

    try {
        // Menu showing if only .fakedev is typed or wrong params
        if (command === 'fakedev' || (!text && !m.quoted)) {
            const p = prefix || "."; // Default to dot if prefix is missing
            return reply(`*🎨 FAKE DEV GENERATOR*\n\n*Usage:*\n${p}fakedev1 <name> <true/false>\n${p}fakedev2 <name>\n${p}fakedev3 <name> <true/false>\n\n*Note:* Reply to an image or provide a URL.`);
        }

        if (msgKey) await conn.sendMessage(from, { react: { text: '⏳', key: msgKey } });
        
        let args = text ? text.trim().split(/\s+/) : [];
        let name = args[0] || "Prova-MD";
        let verified = (args[1] || 'false').toLowerCase();
        let imageUrl = args[2] || null;

        // Image Handling (Media Download & Upload)
        if (!imageUrl) {
            let q = m.quoted ? m.quoted : m;
            let mime = (q.msg || q).mimetype || '';

            if (!/image/.test(mime)) return reply("📸 Please reply to an image or provide a direct image URL!");

            let media = await q.download();
            
            // Upload to Uguu.se for temporary URL
            let form = new FormData();
            form.append('files[]', media, { filename: 'image.jpg' });

            const upRes = await axios.post('https://uguu.se/upload.php', form, {
                headers: { ...form.getHeaders() }
            });

            if (!upRes.data?.files?.[0]?.url) throw new Error("Image upload failed. Try again.");
            imageUrl = upRes.data.files[0].url;
        }

        // API URL Selection
        let apiUrl;
        const base = "https://kayzzidgf.my.id/api/maker";
        const apiKey = "FreeLimit";

        if (command === 'fakedev1') {
            apiUrl = `${base}/fakedev?text=${encodeURIComponent(name)}&image=${encodeURIComponent(imageUrl)}&verified=${verified}&apikey=${apiKey}`;
        } else if (command === 'fakedev3') {
            apiUrl = `${base}/fakedev3?text=${encodeURIComponent(name)}&image=${encodeURIComponent(imageUrl)}&verified=${verified}&apikey=${apiKey}`;
        } else {
            apiUrl = `${base}/fakedev2?url=${encodeURIComponent(imageUrl)}&text=${encodeURIComponent(name)}&apikey=${apiKey}`;
        }

        // Final Delivery
        const finalImg = await axios.get(apiUrl, { responseType: 'arraybuffer' });
        await conn.sendMessage(from, { 
            image: Buffer.from(finalImg.data), 
            caption: `✅ *Generated by Prova-MD*` 
        }, { quoted: m });

        if (msgKey) await conn.sendMessage(from, { react: { text: '✅', key: msgKey } });

    } catch (e) {
        reply(`❌ *Error:* ${e.message}`);
        if (msgKey) await conn.sendMessage(from, { react: { text: '❌', key: msgKey } });
    }
});
                
